<a href="https://colab.research.google.com/github/hritiksth764/END-COURSE-/blob/main/ASSIGNMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.manual_seed(2)

In [ ]:
X = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
Y = torch.Tensor([0, 1, 1, 0]).view(-1,1)

In [ ]:
'''

QUESTION 1 AND QUESTION 2

'''

class XOR(nn.Module):
    def __init__(self, input_dim = 2, output_dim=1):
        super(XOR, self).__init__()
        self.lin1 = nn.Linear(input_dim, 5)
        self.lin3 = nn.Linear(4, output_dim)
        self.lin2 = nn.Linear(5,4)
    
    def forward(self, x):
        x = self.lin1(x)
        x = F.tanh(x)
        x = self.lin2(x)
        x = F.tanh(x)
        x = self.lin3(x)
        # x = F.tanh(x)
        return x

model = XOR()
print(model)
for parameter in model.parameters():
    print(parameter)
print(model.parameters())
from torchsummary import summary
summary(model,(2,2))

XOR(
  (lin1): Linear(in_features=2, out_features=5, bias=True)
  (lin3): Linear(in_features=4, out_features=1, bias=True)
  (lin2): Linear(in_features=5, out_features=4, bias=True)
)
Parameter containing:
tensor([[-0.1045,  0.6300],
        [-0.0445,  0.3834],
        [ 0.5178,  0.3150],
        [-0.6149,  0.5300],
        [ 0.4663, -0.5069]], requires_grad=True)
Parameter containing:
tensor([-0.2521,  0.4813, -0.6874, -0.6198, -0.4792], requires_grad=True)
Parameter containing:
tensor([[ 0.1558, -0.2042, -0.4459,  0.1938]], requires_grad=True)
Parameter containing:
tensor([0.2529], requires_grad=True)
Parameter containing:
tensor([[ 0.1675, -0.3832,  0.4355, -0.0337, -0.4256],
        [-0.0673,  0.2921,  0.2060, -0.0048,  0.3153],
        [-0.4080,  0.3103,  0.4439, -0.2719,  0.0959],
        [-0.0721, -0.3775, -0.0039, -0.1499, -0.3820]], requires_grad=True)
Parameter containing:
tensor([-0.3259,  0.0098,  0.4146,  0.1601], requires_grad=True)
<generator object Module.parameters at 

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1794: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [ ]:
def weights_init(model):
    for m in model.modules():
        if isinstance(m, nn.Linear):
            # initialize the weight tensor, here we use a normal distribution
            m.weight.data.normal_(0, 1)

weights_init(model)

In [ ]:
loss_func = nn.L1Loss()

In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.02, momentum=0.9)

In [ ]:
'''
QUESTION 3
'''
epochs = 2100
steps = X.size(0)
for i in range(epochs):
    for j in range(steps):
        data_point = np.random.randint(X.size(0))
        x_var = Variable(X[data_point], requires_grad=False)
        y_var = Variable(Y[data_point], requires_grad=False)
        
        optimizer.zero_grad()
        y_hat = model(x_var)
        loss = loss_func.forward(y_hat, y_var)
        loss.backward()
        optimizer.step()
        
    if i % 50 == 0:
        print( "Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1794: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


Epoch: 0, Loss: 0.09516441822052002, 
Epoch: 50, Loss: 0.002853214740753174, 
Epoch: 100, Loss: 0.2171483039855957, 
Epoch: 150, Loss: 0.9464837312698364, 
Epoch: 200, Loss: 0.7067776918411255, 
Epoch: 250, Loss: 0.16079634428024292, 
Epoch: 300, Loss: 0.06528884172439575, 
Epoch: 350, Loss: 0.08816272020339966, 
Epoch: 400, Loss: 0.10327553749084473, 
Epoch: 450, Loss: 0.049255698919296265, 
Epoch: 500, Loss: 0.4467812180519104, 
Epoch: 550, Loss: 0.1599169373512268, 
Epoch: 600, Loss: 0.04691249132156372, 
Epoch: 650, Loss: 0.14485764503479004, 
Epoch: 700, Loss: 0.5133978724479675, 
Epoch: 750, Loss: 0.4708113670349121, 
Epoch: 800, Loss: 0.3483259081840515, 
Epoch: 850, Loss: 0.03756040334701538, 
Epoch: 900, Loss: 0.06781625747680664, 
Epoch: 950, Loss: 0.3253958225250244, 
Epoch: 1000, Loss: 0.12247288227081299, 
Epoch: 1050, Loss: 0.2902243733406067, 
Epoch: 1100, Loss: 0.0496525764465332, 
Epoch: 1150, Loss: 0.15494143962860107, 
Epoch: 1200, Loss: 0.17114925384521484, 
Epoch: 